import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { parsePackageLock, discoverWorkspacePackages, isInternalOrNonRegistrySpec } from "../parser";

describe("parsePackageLock & Monorepo Support", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "vuln-test-"));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it("should parse lockfile when directory path is provided", async () => {
    const lockfileContent = JSON.stringify({
      packages: {
        "node_modules/axios": { version: "0.21.1" },
      },
    });
    await fs.writeFile(path.join(tmpDir, "package-lock.json"), lockfileContent, "utf-8");

    const result = await parsePackageLock(tmpDir);
    expect(result).toHaveLength(1);
    expect(result[0]).toEqual({
      package: { name: "axios", ecosystem: "npm" },
      version: "0.21.1",
    });
  });

  it("should parse lockfile when direct lockfile path is provided", async () => {
    const lockfilePath = path.join(tmpDir, "package-lock.json");
    const lockfileContent = JSON.stringify({
      packages: {
        "node_modules/lodash": { version: "4.17.21" },
      },
    });
    await fs.writeFile(lockfilePath, lockfileContent, "utf-8");

    const result = await parsePackageLock(lockfilePath);
    expect(result).toHaveLength(1);
    expect(result[0]).toEqual({
      package: { name: "lodash", ecosystem: "npm" },
      version: "4.17.21",
    });
  });

  it("should support v1 dependencies format and recursively parse nested sub-dependencies", async () => {
    const lockfileContent = JSON.stringify({
      lockfileVersion: 1,
      dependencies: {
        express: {
          version: "4.17.1",
          dependencies: {
            qs: { version: "6.7.0" },
            cookie: {
              version: "0.4.0",
              dependencies: {
                "sub-cookie": { version: "1.0.0" },
              },
            },
          },
        },
      },
    });
    await fs.writeFile(path.join(tmpDir, "package-lock.json"), lockfileContent, "utf-8");

    const result = await parsePackageLock(tmpDir);
    expect(result).toHaveLength(4);
    expect(result).toEqual(
      expect.arrayContaining([
        { package: { name: "express", ecosystem: "npm" }, version: "4.17.1" },
        { package: { name: "qs", ecosystem: "npm" }, version: "6.7.0" },
        { package: { name: "cookie", ecosystem: "npm" }, version: "0.4.0" },
        { package: { name: "sub-cookie", ecosystem: "npm" }, version: "1.0.0" },
      ])
    );
  });

  it("should parse pnpm-lock.yaml when pnpm package manager is selected", async () => {
    const pnpmContent = `
lockfileVersion: '6.0'
packages:
  /express@4.17.1:
    resolution: {integrity: sha512-xxx}
  /lodash@4.17.21:
    resolution: {integrity: sha512-yyy}
`;
    await fs.writeFile(path.join(tmpDir, "pnpm-lock.yaml"), pnpmContent, "utf-8");

    const result = await parsePackageLock(tmpDir, "pnpm");
    expect(result).toEqual(
      expect.arrayContaining([
        { package: { name: "express", ecosystem: "npm" }, version: "4.17.1" },
        { package: { name: "lodash", ecosystem: "npm" }, version: "4.17.21" },
      ])
    );
  });

  it("should parse yarn.lock when yarn package manager is selected", async () => {
    const yarnContent = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.
# yarn lockfile v1

"express@^4.17.0":
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz"
`;
    await fs.writeFile(path.join(tmpDir, "yarn.lock"), yarnContent, "utf-8");

    const result = await parsePackageLock(tmpDir, "yarn");
    expect(result).toHaveLength(1);
    expect(result[0]).toEqual({
      package: { name: "express", ecosystem: "npm" },
      version: "4.17.1",
    });
  });

  it("should identify internal workspace and file/link protocols correctly", () => {
    expect(isInternalOrNonRegistrySpec("workspace:*")).toBe(true);
    expect(isInternalOrNonRegistrySpec("workspace:^1.0.0")).toBe(true);
    expect(isInternalOrNonRegistrySpec("file:../some-pkg")).toBe(true);
    expect(isInternalOrNonRegistrySpec("link:./packages/ui")).toBe(true);
    expect(isInternalOrNonRegistrySpec("portal:./packages/core")).toBe(true);
    expect(isInternalOrNonRegistrySpec("git+https://github.com/foo/bar.git")).toBe(true);
    expect(isInternalOrNonRegistrySpec("^4.17.1")).toBe(false);
    expect(isInternalOrNonRegistrySpec("1.2.3")).toBe(false);
  });

  it("should discover sub-packages in monorepo workspaces and audit third-party packages while filtering workspace protocols", async () => {
    // Create root package.json with workspaces
    await fs.writeFile(
      path.join(tmpDir, "package.json"),
      JSON.stringify({ name: "root-monorepo", workspaces: ["packages/*"] }),
      "utf-8"
    );

    // Create sub-package A
    const subPkgADir = path.join(tmpDir, "packages", "pkg-a");
    await fs.mkdir(subPkgADir, { recursive: true });
    await fs.writeFile(
      path.join(subPkgADir, "package.json"),
      JSON.stringify({
        name: "@monorepo/pkg-a",
        dependencies: {
          axios: "^0.21.1",
          "@monorepo/pkg-b": "workspace:*",
          localpkg: "file:../localpkg",
        },
      }),
      "utf-8"
    );

    // Create sub-package B
    const subPkgBDir = path.join(tmpDir, "packages", "pkg-b");
    await fs.mkdir(subPkgBDir, { recursive: true });
    await fs.writeFile(
      path.join(subPkgBDir, "package.json"),
      JSON.stringify({
        name: "@monorepo/pkg-b",
        dependencies: {
          lodash: "^4.17.21",
        },
      }),
      "utf-8"
    );

    const discoveredDirs = await discoverWorkspacePackages(tmpDir);
    expect(discoveredDirs).toHaveLength(2);

    const queries = await parsePackageLock(tmpDir, "npm");
    expect(queries).toEqual(
      expect.arrayContaining([
        { package: { name: "axios", ecosystem: "npm" }, version: "0.21.1" },
        { package: { name: "lodash", ecosystem: "npm" }, version: "4.17.21" },
      ])
    );

    // Internal workspace references should be filtered out
    const queryNames = queries.map((q) => q.package.name);
    expect(queryNames).not.toContain("@monorepo/pkg-b");
    expect(queryNames).not.toContain("localpkg");
  });
});