import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { parsePackageLock } from "../parser";

describe("parsePackageLock", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "vuln-test-"));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  it("should parse lockfile when directory path is provided", async () => {
    const lockfileContent = JSON.stringify({
      packages: {
        "node_modules/axios": { version: "0.21.1" },
      },
    });
    await fs.writeFile(path.join(tmpDir, "package-lock.json"), lockfileContent, "utf-8");

    const result = await parsePackageLock(tmpDir);
    expect(result).toHaveLength(1);
    expect(result[0]).toEqual({
      package: { name: "axios", ecosystem: "npm" },
      version: "0.21.1",
    });
  });

  it("should parse lockfile when direct lockfile path is provided", async () => {
    const lockfilePath = path.join(tmpDir, "package-lock.json");
    const lockfileContent = JSON.stringify({
      packages: {
        "node_modules/lodash": { version: "4.17.21" },
      },
    });
    await fs.writeFile(lockfilePath, lockfileContent, "utf-8");

    const result = await parsePackageLock(lockfilePath);
    expect(result).toHaveLength(1);
    expect(result[0]).toEqual({
      package: { name: "lodash", ecosystem: "npm" },
      version: "4.17.21",
    });
  });

  it("should support v1 dependencies format and recursively parse nested sub-dependencies", async () => {
    const lockfileContent = JSON.stringify({
      lockfileVersion: 1,
      dependencies: {
        express: {
          version: "4.17.1",
          dependencies: {
            qs: { version: "6.7.0" },
            cookie: {
              version: "0.4.0",
              dependencies: {
                "sub-cookie": { version: "1.0.0" },
              },
            },
          },
        },
      },
    });
    await fs.writeFile(path.join(tmpDir, "package-lock.json"), lockfileContent, "utf-8");

    const result = await parsePackageLock(tmpDir);
    expect(result).toHaveLength(4);
    expect(result).toEqual(
      expect.arrayContaining([
        { package: { name: "express", ecosystem: "npm" }, version: "4.17.1" },
        { package: { name: "qs", ecosystem: "npm" }, version: "6.7.0" },
        { package: { name: "cookie", ecosystem: "npm" }, version: "0.4.0" },
        { package: { name: "sub-cookie", ecosystem: "npm" }, version: "1.0.0" },
      ])
    );
  });

  it("should parse pnpm-lock.yaml when pnpm package manager is selected", async () => {
    const pnpmContent = `
lockfileVersion: '6.0'
packages:
  /express@4.17.1:
    resolution: {integrity: sha512-xxx}
  /lodash@4.17.21:
    resolution: {integrity: sha512-yyy}
`;
    await fs.writeFile(path.join(tmpDir, "pnpm-lock.yaml"), pnpmContent, "utf-8");

    const result = await parsePackageLock(tmpDir, "pnpm");
    expect(result).toEqual(
      expect.arrayContaining([
        { package: { name: "express", ecosystem: "npm" }, version: "4.17.1" },
        { package: { name: "lodash", ecosystem: "npm" }, version: "4.17.21" },
      ])
    );
  });

  it("should parse yarn.lock when yarn package manager is selected", async () => {
    const yarnContent = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.
# yarn lockfile v1

"express@^4.17.0":
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz"
`;
    await fs.writeFile(path.join(tmpDir, "yarn.lock"), yarnContent, "utf-8");

    const result = await parsePackageLock(tmpDir, "yarn");
    expect(result).toHaveLength(1);
    expect(result[0]).toEqual({
      package: { name: "express", ecosystem: "npm" },
      version: "4.17.1",
    });
  });
});